heckle.cabal: bump to latest optparse-applicative-0.13
optparse-applicative-0.13 stopped exporting own (<>)
operator in favour of Data.Monoid instance.
The only place required a tweak:

```
  src/Main.hs:31:32: error:
    • Variable not in scope:
        (<>) :: InfoMod a1 -> InfoMod a0 -> InfoMod Command
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative),
        ‘<$’ (imported from Options.Applicative)
```

Signed-off-by: Sergei Trofimovich <siarheit@google.com>